### ISSUE TITLE
When cancelling everything freezes

### ISSUE THREAD

**Issue by chris18020** [Project-Sloth/progressbar#4]
When cancelling everything freezes up. Also if you cancel and right click the Windows Print console pops up as well.
![unknown](https://user-images.githubusercontent.com/63619539/169651976-2794558c-ab62-4b2d-b778-9b2c30200dd2.png)

**Comment by skrimxyz** [comment]
Lmao I got the same issue

**Comment by gitgaming21** [comment]
![image](https://user-images.githubusercontent.com/86384399/183257755-62b015f6-acf2-40dc-b0c5-321b51df5ebb.png)
make sure you have added the end, function() --cancelled like iv done well fix this
