### ISSUE TITLE
inventory not disabled when using an item 

### ISSUE THREAD

**Issue by SKITTLE6969** [Project-Sloth/progressbar#5]
inventory isn't disabled when using an item people can open inventory and drop items

**Comment by davidxd33** [comment]
You should be first checking if the player has the item on the server side before doing anything. The client sided measure to not open the inventory shouldn't be your only protection against this.

**Comment by SKITTLE6969** [comment]
yes true but everything bypasses when i replaced this instead of default progressbar and it dosent seem to stop ppl from opening the inventory like the default one supposed to do
